services:
  - name: dietaapp
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    disk:
      name: dietaapp-db
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - backend/**
        - render.yaml
        - cabal.project
      ignoredPaths:
        - README.md
        - frontend/**
