cabal-version:      2.4
name:               dietaapp
version:            0.1.0.0

executable dietaapp
    main-is:          main.hs
    other-modules:    Banco, Login, Calculate, Alimento, Plano

    build-depends:    base        >=4.14 && <5,
                      scotty,
                      aeson,
                      wai-cors,
                      sqlite-simple,
                      http-types,
                      directory

    ghc-options:      -threaded
    default-language: Haskell2010
    default-extensions: LambdaCase
